### ISSUE TITLE
Broken link on wiki home

### ISSUE THREAD

**Issue by chuahou** [weighanchor4414/Documentations#1]
The home page of the wiki has a link under **Pages in the wiki** to [Running Ubuntu on Raspberry Pi](https://github.com/weighanchor4414/linux-stuff/wiki/Running-Ubuntu-Server-on-Raspberry-Pi-3-4), but the actual page has [a different URL](https://github.com/weighanchor4414/Documentations/wiki/Running-Ubuntu-Server-on-Raspberry-Pi-2,-3-or-4).

Hence the page can be accessed via the link in the Pages sidebar but not via the link in the Home page.

**Comment by weighanchor4414** [comment]
Link has been fixed :)
